background = #1f0605
foreground = #e4edc8
background-opacity = 0.888
cursor-color = #e4edc8
cursor-text = #1f0605
selection-background = #391808
selection-foreground = #e4edc8

palette = 0=#1f0605
palette = 1=#9d1a19
palette = 2=#68a05f
palette = 3=#b9924a
palette = 4=#8d7763
palette = 5=#c6a15b
palette = 6=#a8ccc8
palette = 7=#e4edc8
palette = 8=#391808
palette = 9=#ed5c5b
palette = 10=#a6cba1
palette = 11=#e4c07a
palette = 12=#cbb79b
palette = 13=#ebcf9e
palette = 14=#e1efed
palette = 15=#ffffff
