## name : Ristretto

background_opacity      0.888

foreground              #e4edc8

background              #1f0605


selection_foreground    #e4edc8

selection_background    #391808


cursor                  #e4edc8

cursor_text_color       #1f0605

url_color               #c6a15b

active_border_color     #c6a15b
inactive_border_color   #8d7763
bell_border_color       #8d7763

active_tab_foreground   #1f0605
active_tab_background   #c6a15b
inactive_tab_foreground #e4edc8
inactive_tab_background #1f0605
tab_bar_background      #391808

mark1_foreground        #1f0605
mark1_background        #c6a15b
mark2_foreground        #1f0605
mark2_background        #8d7763
mark3_foreground        #1f0605
mark3_background        #cbb79b

color0  #1f0605

color8  #391808


color1  #9d1a19

color9  #ed5c5b


color2  #68a05f

color10 #a6cba1


color3  #b9924a

color11 #e4c07a


color4  #8d7763

color12 #cbb79b


color5  #c6a15b

color13 #ebcf9e


color6  #a8ccc8

color14 #e1efed


color7  #e4edc8

color15  #ffffff
