-- Generated by scripts/hypr2lua.
-- Source: omarchy-ghosts-i-theme/hyprland.conf

local activeBorderStart = "rgb(4e3024)"
local activeBorderShoulder = "rgb(8d623b)"
local activeBorderMid = "rgb(c19359)"
local activeBorderFlare = "rgb(d9b67e)"
local activeBorderEnd = "rgb(e6d7c3)"

hl.config({
  general = {
    col = {
      active_border = {
        colors = { activeBorderStart, activeBorderShoulder, activeBorderMid, activeBorderFlare, activeBorderEnd, activeBorderFlare, activeBorderMid, activeBorderShoulder, activeBorderStart },
        angle = 33,
      },
    },
    gaps_in = 8,
    gaps_out = 16,
  },
  decoration = {
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
      ignore_opacity = true,
      new_optimizations = true,
      xray = true,
      noise = 0.06,
      contrast = 0.92,
      brightness = 0.82,
      vibrancy = 0.08,
      vibrancy_darkness = 0.15,
    },
    shadow = {
      enabled = true,
      range = 21,
      render_power = 4,
      sharp = false,
      color = "rgba(000000cc)",
      color_inactive = "rgba(000000aa)",
      offset = "2 3",
      scale = 1.01,
    },
  },
  group = {
    col = {
      border_active = {
        colors = { activeBorderStart, activeBorderShoulder, activeBorderMid, activeBorderFlare, activeBorderEnd, activeBorderFlare, activeBorderMid, activeBorderShoulder, activeBorderStart },
        angle = 38,
      },
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("ghostEase", { type = "bezier", points = { { 0.14, 0.90 }, { 0.18, 1.0 } } })
hl.curve("ghostFade", { type = "bezier", points = { { 0.38, 0.0 }, { 0.14, 1.0 } } })

hl.animation({
  leaf = "border",
  enabled = true,
  speed = 3.8,
  bezier = "ghostEase",
})
hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3.6,
  bezier = "ghostEase",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3.2,
  bezier = "ghostEase",
  style = "popin 97%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 1.7,
  bezier = "ghostFade",
  style = "popin 99%",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 3.2,
  bezier = "ghostFade",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 2.8,
  bezier = "ghostFade",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4.2,
  bezier = "ghostFade",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 2.0,
  bezier = "ghostEase",
  style = "fade",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 1.9,
  bezier = "ghostFade",
  style = "fade",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 3.0,
  bezier = "ghostEase",
  style = "slidefade",
})
hl.animation({
  leaf = "specialWorkspace",
  enabled = true,
  speed = 3.8,
  bezier = "ghostEase",
  style = "fade",
})

hl.layer_rule({
  no_anim = false,
  match = {
    namespace = "walker",
  },
})
