background = #1f0605
foreground = #e4edc8
background-opacity = 0.888
cursor-color = #e4edc8
cursor-text = #1f0605
selection-background = #391808
selection-foreground = #e4edc8

palette = 0=#1f0605
palette = 1=#9d1a19
palette = 2=#4d7a63
palette = 3=#b46a3c
palette = 4=#6b3a33
palette = 5=#d18b47
palette = 6=#8b4f3f
palette = 7=#e4edc8
palette = 8=#391808
palette = 9=#ed5c5b
palette = 10=#739682
palette = 11=#e0a35a
palette = 12=#9a5643
palette = 13=#ebb16d
palette = 14=#c79678
palette = 15=#ffffff
