## name : Ristretto

background_opacity      0.888

foreground              #e4edc8

background              #1f0605


selection_foreground    #e4edc8

selection_background    #2b0f12




cursor                  #e4edc8

cursor_text_color       #1f0605

url_color               #c6a15b

active_border_color     #c6a15b
inactive_border_color   #8d7763
bell_border_color       #8d7763

active_tab_foreground   #1f0605
active_tab_background   #c6a15b
inactive_tab_foreground #e4edc8
inactive_tab_background #1f0605
tab_bar_background      #391808

mark1_foreground        #1f0605
mark1_background        #c6a15b
mark2_foreground        #1f0605
mark2_background        #8d7763
mark3_foreground        #1f0605
mark3_background        #cbb79b

color0  #1f0605

color8  #391808


color1  #9d1a19

color9  #ed5c5b


color2  #4d7a63



color10 #739682




color3  #b46a3c



color11 #e0a35a




color4  #6b3a33



color12 #9a5643




color5  #d18b47



color13 #ebb16d




color6  #8b4f3f



color14 #c79678




color7  #e4edc8

color15  #ffffff
