background = #160c10
foreground = #e7dfd2
background-opacity = 0.888
cursor-color = #e4edc8
cursor-text = #1f0605
selection-background = #391808
selection-foreground = #e4edc8

palette = 0=#160c10
palette = 1=#8f2438
palette = 2=#3f6b63
palette = 3=#d8923b
palette = 4=#5c4a58
palette = 5=#8a4a64
palette = 6=#9b7a5f
palette = 7=#e7dfd2
palette = 8=#3a2830
palette = 9=#b03a52
palette = 10=#5a8a7f
palette = 11=#ebb15a
palette = 12=#7a6574
palette = 13=#b06b8b
palette = 14=#c7a27d
palette = 15=#f5ede2
