$activeBorderColor = rgb(d8923b)





general {
    col.active_border = $activeBorderColor
    gaps_in = 8
    gaps_out = 16
}

decoration {
    blur {
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        xray = true
        noise = 0.02
        contrast = 0.92
        brightness = 0.82
        vibrancy = 0.08
        vibrancy_darkness = 0.15
    }

    shadow {
        enabled = true
        range = 24
        render_power = 4
        sharp = false
        ignore_window = true
        color = rgba(000000dd)
        color_inactive = rgba(000000aa)
        offset = 1 3
        scale = 1.0
    }
}

group {
    col.border_active = $activeBorderColor
}
