## name : Ristretto

background_opacity      0.888

foreground              #e7dfd2


background              #160c10



selection_foreground    #f5ede2


selection_background    #2a0f18





cursor                  #e7dfd2


cursor_text_color       #1f0605

url_color               #c6a15b

active_border_color     #c6a15b
inactive_border_color   #8d7763
bell_border_color       #8d7763

active_tab_foreground   #1f0605
active_tab_background   #c6a15b
inactive_tab_foreground #e4edc8
inactive_tab_background #1f0605
tab_bar_background      #391808

mark1_foreground        #1f0605
mark1_background        #c6a15b
mark2_foreground        #1f0605
mark2_background        #8d7763
mark3_foreground        #1f0605
mark3_background        #cbb79b

color0  #160c10


color8  #3a2830



color1  #8f2438


color9  #b03a52



color2  #3f6b63




color10 #5a8a7f





color3  #d8923b




color11 #ebb15a





color4  #5c4a58




color12 #7a6574





color5  #8a4a64




color13 #b06b8b





color6  #9b7a5f




color14 #c7a27d





color7  #e7dfd2


color15  #f5ede2

