background = #1f0605
foreground = #e4edc8
background-opacity = 0.888
cursor-color = #e4edc8
cursor-text = #1f0605
selection-background = #391808
selection-foreground = #e4edc8

palette = 0=#1f0605
palette = 1=#9d1a19
palette = 2=#5b8a63
palette = 3=#a95a32
palette = 4=#7a4a36
palette = 5=#c9834a
palette = 6=#8f6a4f
palette = 7=#e4edc8
palette = 8=#391808
palette = 9=#ed5c5b
palette = 10=#7fa287
palette = 11=#d79a5d
palette = 12=#a96d4e
palette = 13=#e0a56e
palette = 14=#c7a889
palette = 15=#ffffff
